# Generated by Django 3.0.5 on 2020-04-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='theme_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
