# Generated by Django 3.0.5 on 2020-04-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_banner_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpagebanner',
            name='banner_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
