# Generated by Django 3.0.5 on 2020-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paytm_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
