# Generated by Django 3.0.5 on 2020-04-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('match_type', models.CharField(choices=[('Solo', 'Solo'), ('Duo', 'Duo'), ('Squad', 'Squad')], max_length=50)),
                ('tournament_type', models.CharField(choices=[('PUBG Mobile', 'PUBG Mobile'), ('PUBG Mobile Lite ', 'PUBG Mobile Lite')], max_length=50)),
                ('map', models.CharField(choices=[('PUBG MOBILE', (('Erangle', 'Erangle'), ('Sanhok', 'Sanhok'), ('Miramer', 'Miramer'), ('Vikendi', 'Vikendi'), ('TDM : Warehouse', 'TDM : Warehouse'))), ('PUBG MOBILE LITE', (('Varenge', 'Varenge'), ('Golden', 'Woods'), ('TDM : Warehouse', 'TDM : Warehouse')))], max_length=100)),
                ('date_of_match', models.DateTimeField()),
                ('winning_prize', models.IntegerField()),
                ('per_kill', models.IntegerField()),
                ('entry_fee', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
