# Generated by Django 3.0.5 on 2020-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20200416_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bg_picture',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
