# Generated by Django 3.0.5 on 2020-04-16 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0003_auto_20200416_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='user_list',
            field=models.ManyToManyField(blank=True, related_name='user_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
