# Generated by Django 3.0.5 on 2020-04-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20200417_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(blank=True, choices=[('PUBG Mobile', 'PUBG Mobile'), ('PUBG Mobile Lite', 'PUBG Mobile Lite')], max_length=50, null=True),
        ),
    ]
